### ISSUE TITLE
Add a guest name generator

### ISSUE THREAD

**Issue by loicteixeira** [loicteixeira/gj-unity-api#19]
Guest name generator! When saving a score for a guest, it will show the name of the guest followed by "(guest)" on the website, but because the default name is "Guest", it actually shows "Guest (guest)" which is pretty lame. Unless you specify a name yourself, it would be nice to add random names like Mario/Luigi/Sonic/etc (and possibly allow the use of custom lists to match a game universe).

**Comment by Yecats** [comment]
It would also be nice to some how increment the guest number based on how many have submitted. So, the first guest is "Guest1", the second is "Guest2", etc.

**Comment by loicteixeira** [comment]
There is no way to know how many guests have played the game before so incrementing it would be quite hard unfortunately. Data Storage could potentially be used but I'm not sure it is worth it.

**Comment by loicteixeira** [comment]
Issues are now tracked at [InfectedBytes/gj-unity-api/issues](https://github.com/InfectedBytes/gj-unity-api/).
