### ISSUE TITLE
NullReferenceException in editor on play

### ISSUE THREAD

**Issue by JVAndie** [loicteixeira/gj-unity-api#20]
This happens if you haven't gone to the settings yet. If you went ones to the settings it gone.

the error goes to the start block with this in it 
"// Do not try this at home! Seriously, you shouldn't."
so could be code is temporary

![editor log](https://cloud.githubusercontent.com/assets/10909816/7105556/dbd238c8-e11f-11e4-8739-b5210ce40176.PNG)

**Comment by loicteixeira** [comment]
See I wasn't lying, this is dangerous code ahah!
Seriously thanks for your feedback.

**Comment by loicteixeira** [comment]
Argh.. I fat fingered the issue number in the commit 22eb39b comment. This is actually 29a256a who really fix the issue.
