### ISSUE TITLE
DebugUser & DebugToken

### ISSUE THREAD

**Issue by orcolom** [loicteixeira/gj-unity-api#32]
there is no safe way to get DebugUser and DebugToken.
this would handy in some cases.

Or allow to access a 
'GJAPI.object.user DebugUser;'

this should protect it to not work outside of editor. (with my c++ knowledge)
`
get{ 
#if  UNITY_EDITOR
    return DebugUser;
#else
    return "";
#endif
}
`

there may be better ways to do this.  (are probably)

**Comment by loicteixeira** [comment]
At the moment, Manager.DebugUser and Manager.DebugToken are only created when you are inside the editor but are private. I guess I could indeed make it public if people believe it can be useful.
