### ISSUE TITLE
Add a create account to Sign In window

### ISSUE THREAD

**Issue by ghost** [loicteixeira/gj-unity-api#39]
and link them to 
(wttf.)gamejolt.com/join
http://gamejolt.com/auth/sign_up/

or ingame if the new gamejolt api will allow that

**Comment by loicteixeira** [comment]
Great idea! Unfortunately the API does not allow that so it will only be a link to the sign up page.

**Comment by loicteixeira** [comment]
Issues are now tracked at [InfectedBytes/gj-unity-api/issues](https://github.com/InfectedBytes/gj-unity-api/).
