### ISSUE TITLE
Highscore Screen not showing highscore

### ISSUE THREAD

**Issue by sebasrez** [loicteixeira/gj-unity-api#47]
When I show the highscore screen using the gamejolt API it only displays the logo, close, and the table name but not the users and their scores.

![capture](https://cloud.githubusercontent.com/assets/6834938/8737723/724247cc-2c79-11e5-826b-c894637b87ac.png)

**Comment by loicteixeira** [comment]
Summing up the previous discussion on GameJolt, deleting the gameobject/scripts and reimporting it again initially solved the problem but it appeared again the next time the game was run.

**Comment by loicteixeira** [comment]
- Is the HighScore table also named 'Rock Paper Scissors'? Because the tab should display the name of the table, not the name of the game.
- Can you try to create another table on the GameJolt Dashboard and see what happen?

**Comment by sebasrez** [comment]
1. Thats the name of the table not the name of the game. Sorry about that
2. I created another table and when I click between the two to show score, the score and names appear for a second then disappear.

**Comment by sebasrez** [comment]
Here is my script I am using
http://pastebin.com/kmedNWha

// (c) Copyright HutongGames, LLC 2010-2013. All rights reserved.

using UnityEngine;
using System.Collections;

namespace HutongGames.PlayMaker.Actions
{
	[ActionCategory("Gamejolt")]
	[Tooltip("Shows the Gamejolt Api Highscore screen.")]
	public class ShowHighscore : FsmStateAction
	{

		public override void OnEnter(){
            GameJolt.UI.Manager.Instance.ShowLeaderboards(); 
			Finish();
		}
	}
}

**Comment by loicteixeira** [comment]
Oh right I forgot you are using PlayMaker.
I'll have a look as soon as I can but I'm not really familiar with PlayMaker so I'm not sure I'll be able to find anything before the Jam ;(

**Comment by sebasrez** [comment]
I figured it out. It's the Use Caching enabled that removes it. Once I disable that it works. In the latest version I think it was automatically enabled.

**Comment by loicteixeira** [comment]
It's good that you could make it work.

I don't understand what's going on here but that should give me some lead to investigate. Thanks for your help.

**Comment by Yecats** [comment]
This actually happened to me the first two times I tried it.. then the third it worked fine. (I didn't do anything different, just clicked the button a few times.) After that I haven't had it happen a single time.
