### ISSUE TITLE
ShowLeaderboards callback don't work

### ISSUE THREAD

**Issue by michidk** [loicteixeira/gj-unity-api#51]
If i execute the following code:
`
GameJolt.UI.Manager.Instance.ShowLeaderboards((bool test) => { Debug.Log("A very sad callback :c");});
`
 And i close the Leaderboard by pressing the given close button (from the GameJoltAPI-Prefab), nothing happens.

**Comment by WizzardMaker** [comment]
You have to go to Plugins/GameJolt/Scripts/UI/Controllers and in LeaderboardsWindow.ch you have to modify this piece of Code:
		override public void Show(Action<bool> callback)
		{
			animator.SetTrigger("Leaderboards");
			animator.SetTrigger("ShowLoadingIndicator");
			this.callback = callback; // <- Add this
			//...
		}

**Comment by michidk** [comment]
Okay, i implmented the callback myself, but your fix is better. Just, tested, works fine. Should i open a PR or do you want to do it?

**Comment by WizzardMaker** [comment]
You can do it, I am just a stranger who saw your issue and wanted to help

**Comment by michidk** [comment]
Haha, awesome :D Thank you!

**Comment by loicteixeira** [comment]
Good job guys :+1:
Thanks @michidk for the issue and pull request and thanks @WizzardMaker for helping him!
