### ISSUE TITLE
Update to Sign In Documentation

### ISSUE THREAD

**Issue by Yecats** [loicteixeira/gj-unity-api#55]
This is more of a quick update to the documentation for those learning how to work with GameJolt for the first time. I didn't realize that "token" was actually a token. I thought it wanted my password and you called it something silly. :) So, I spent about 20 minutes trying to debug then as I was giving up on your library I saw my token on the website. It'd be super helpful if you could add a quick explanation to what that is in your documentation.

**Comment by loicteixeira** [comment]
You're not the first one to get confused. I'll add a note about it.
