### ISSUE TITLE
Sign in failure - Invaid login information

### ISSUE THREAD

**Issue by Yecats** [loicteixeira/gj-unity-api#57]
Just released a game on GameJolt with your library and I have some users reporting that the sign in is failing with incorrect token. One person was a buddy, who wasn't able to sign in (tried lots of times) and then gave me his credentials to test. I could sign in just fine with them. He tried again and failed.

This happened in both standalone and Unity web player builds.

**Comment by loicteixeira** [comment]
Looking at your published game on Game Jolt, I assume you are talking about [Dumpster Dash](http://gamejolt.com/games/dumpster-dash/82186)?

I tried the Desktop version and it just worked fine. Regarding the WebPlayer and WebGL versions, you shouldn't ask the user to sign in as they are automatically signed in (the API is able to recognize who's signed in on the website and sign that person in the game).

I agree that the current error message is not great as it says "wrong username or password" when it should says "user already logged in" and will probably do something about it in future versions.

**Comment by Yecats** [comment]
This actually happened on both the web and the desktop version, so I don't think that is the problem. I didn't realize the sign in was automatic for the web versions, so I'll go and correct that behavior.

**Comment by loicteixeira** [comment]
I can't reproduce it. Please try to obtain [logs](http://docs.unity3d.com/Manual/LogFiles.html) from them so we can see what the error is.

**Comment by Yecats** [comment]
Sorry, I've been out of town - I'll try to get some logs this week for you!
