### ISSUE TITLE
Guest Scoring not working 

### ISSUE THREAD

**Issue by thepolishdane** [loicteixeira/gj-unity-api#58]
So i have a webbased Unity game and im using this API.

And the signed in add score function works fine.. But when a user is not signed it:

bool isSignedIn = GameJolt.API.Manager.Instance.CurrentUser != null;

if that "isSignedIn" is not true, my scripts uses the add function with the guest name. 
And that only returns this error message : 

"Guests are not allowed to enter scores for this game."
UnityEngine.Debug:LogWarning(Object)
GameJolt.API.Core.Response:.ctor(WWW, ResponseFormat) (at Assets/Plugins/GameJolt/Scripts/API/Core/Response.cs:60)
GameJolt.API.<GetRequest>c__Iterator0:MoveNext() (at Assets/Plugins/GameJolt/Scripts/API/Manager.cs:108)

I have no idea what im doing wrong, but i would say nothing ? i can't find anywhere where one is supposed to activate "guest scoring" or am i blind ?? :( 

Plz send help.
Thx

**Comment by loicteixeira** [comment]
You can enable Guest Scoring on the Game Jolt dashboard.

1. Navigate to `Your Game > Game API > Scores`.
1. Click on the scoreboard you want to edit, it should expand and show the edit form.
1. Set `Guest Scoring` to `Yes`.

Let me know if that fix your issue.

**Comment by thepolishdane** [comment]
THANK YOU !  :D i could really not find this information anywhere :D dunno im just stupid and blind :D but would be nice to have in the tutorial file :) When its off as default :) 

THX  anyway :) u da best.

**Comment by loicteixeira** [comment]
I'll see where it makes sense to include a note. Maybe the video tutorial..
