### ISSUE TITLE
LeaderboardsWindows class callback is always null

### ISSUE THREAD

**Issue by killerbigpoint** [loicteixeira/gj-unity-api#61]
I can't remember which window it was but im guessing because i already fixed it myself

GameJolt.API.Scores.GetTables (LeaderboardWindows) is missing a (this.callback = callback;)

or

GameJolt.API.Trophies.Get (TrophiesWindows) is missing a (this.callback = callback;)

**Comment by loicteixeira** [comment]
Thanks for the heads up. This has been fixed (see #51) but I still need to produce a release.
