### ISSUE TITLE
Upload on the Unity Asset Store

### ISSUE THREAD

**Issue by loicteixeira** [loicteixeira/gj-unity-api#63]
It's about time!

**Comment by InfectedBytes** [comment]
In order to upload a package to the store, one must provide at least one demo scene with it.
Furthermore we could not upload two root folders, therefore the demo folder must be inside another folder, like our Gamejolt folder.
So I would propose to move the Test folder to our GameJolt folder.

Should I add the needed AssetStore images to the repository?

**Comment by loicteixeira** [comment]
Something to be aware of with Unity, is when you move files around because installing a new version of a package is like unzipping on top of a folder, which means that new files get added but old files don't get deleted. Therefore you might have duplicated classes which will cause errors in the console and prevent the games from booting. If that's the case, we should warn the users in the release notes.

But it looks like it would only require the `test` (or `demo` folder) to move inside of another one, and given that those scenes were never publicly released before it should be fine.

AssetStore images can be added to the repo yes. Probably at the root alonside to the documentation?

However, please note that while the work can be done, I will not submit the package to the Unity AssetStore as long as I maintain the project. This would be one more thing to take care of for every release and this is not something I can afford at the moment. This will be for the next maintainer to do :)

**Comment by InfectedBytes** [comment]
moving a file from one folder to another shouldn't be a problem, because of the guid system of unity.
But deleting a file could be little problem.

I will take care of it :-P

**Comment by InfectedBytes** [comment]
I forgot to add a "closes #82" comment in the pull request, so you have to close this issue manually.

**Comment by loicteixeira** [comment]
Well, although it is ready for the Asset Store, the package still isn't so I'll keep it open for now.

**Comment by InfectedBytes** [comment]
I'll submit it now as version 2.3.0
The Asset Store team typically needs about 5-10 business days in order to review a submitted package.

**Comment by loicteixeira** [comment]
A first submission might take a little bit longer than that I imagine, but anyway, we might want to decide whether the package will still be distributed via GameJolt and GitHub (I think it should) and we should make sure the same build is submitted everywhere. I'll try to create 2.3.0 this afternoon.

**Comment by loicteixeira** [comment]
Also remember that the package has to be generated with Unity 5.0.1 as it is the minimum requirement at the moment (but see #83 for discussions about bumping that version).

**Comment by loicteixeira** [comment]
`2.3.0` package can be downloaded for the [corresponding release](https://github.com/loicteixeira/gj-unity-api/releases/tag/v2.3.0).

**Comment by loicteixeira** [comment]
Issues are now tracked at [InfectedBytes/gj-unity-api/issues](https://github.com/InfectedBytes/gj-unity-api/).
