### ISSUE TITLE
Unable to Sign Into GameJolt

### ISSUE THREAD

**Issue by Nanapus** [loicteixeira/gj-unity-api#66]
Every time I attempt a sign in with GameJolt, I get thrown an error of "The signature you entered for the request is invalid." I have not tested this in a built version of my game, only in the editor.

**Comment by loicteixeira** [comment]
Did you fill the game id and private key in the settings? http://loicteixeira.github.io/gj-unity-api/tutorial.html

**Comment by Nanapus** [comment]
In order to fill these out, do I need to set up a game on GameJolt and would it provide me with what to place in?

**Comment by Nanapus** [comment]
Thanks for the help (even if it was minimal support). I found out how to use game id's and keys and solved my issue,
