### ISSUE TITLE
Settings menu don't show up

### ISSUE THREAD

**Issue by loicteixeira** [loicteixeira/gj-unity-api#67]
![cw6f4rgveaarhzf](https://cloud.githubusercontent.com/assets/6834938/20187347/c38d5e38-a7d8-11e6-9943-143bb214c130.jpg)

Reported by @Haddicus on [Twitter](https://twitter.com/Haddicus/status/796749986398605313).

**Comment by loicteixeira** [comment]
I'm confused. by the look of the project tree, it seems that:
1. you might be using the API version 1.x which does not have a settings menu.
1. some files are missing.

Regarding the first point, the only reason to use 1.x at the moment is if you need support of an old Unity version (>= 3.5 < 5):
- If this is a requirement, the corresponding documentation can be downloaded on the [project page](http://gamejolt.com/games/unity-api/15887) (under `Unity API v1 [Deprecated]`, select `Download` then `GJAPI_1.2.x_Documentation.zip`).
- If this is not a requirement, please delete the `GameJoltAPI` folder, download and install the [latest version](http://gamejolt.com/games/unity-api/15887) (2.1.1 at the moment).

As for the second point, I'd recommend deleting the `GameJoltAPI` folder, download the version of your choice on the [project page](http://gamejolt.com/games/unity-api/15887) and reinstall.

**Comment by Haddicus** [comment]
Oddly enough - I removed the files, re-downloaded/re-added the files, and the menu system showed up. I did read the site on selecting the appropriate item in the API, and after rechecking, it looks as if I selected the wrong version when downloading (no clue how that happened - completely my fault). Thanks for getting this information to me so quickly! I appreciate it.

**Comment by loicteixeira** [comment]
Glad you could get it to work.
