### ISSUE TITLE
Login is failing after Unity update

### ISSUE THREAD

**Issue by loicteixeira** [loicteixeira/gj-unity-api#73]
Trying to log via the UI will display `Wrong username and/or token.` (see [video](https://twitter.com/SpencerFossett/status/862341818029150208)).

Unity v2017.1.0b5, GJAPI v2.1.2.

**Comment by loicteixeira** [comment]
Technically the window will show the `Wrong username and/or token.` message, [regardless of the error](https://github.com/loicteixeira/gj-unity-api/blob/a34798ed82784770f77650f198109563ba9337d7/Assets/Plugins/GameJolt/Scripts/UI/Controllers/SignInWindow.cs#L54-L55).

One way to learn a bit more about the underlying issue, would be to replace [this](https://github.com/loicteixeira/gj-unity-api/blob/a34798ed82784770f77650f198109563ba9337d7/Assets/Plugins/GameJolt/Scripts/API/Objects/User.cs#L223-L227) with:
```csharp
if (response.success)
{
	Manager.Instance.CurrentUser = this;
	Get();
}
else
{
	Debug.Log(response.json);
}
```

**Comment by TheFossett** [comment]
There is another problem where sometimes you are able to upload a guest score to the first leaderboard you made but it doesn't work 100% of the time.
This problem could still tie in with the current problem not to sure :/

Hope this helps :)
Spencer Fossett

**Comment by DanielJMus** [comment]
Hey lads, I just fixed this.

I noticed that the Debug.LogError for the www.error was a blank message, upon reading the documentation for Www.error I noticed that they pointed this out.

In Response.cs at line 83, simply change:

`if (www.error != null)`

at the top of the Response function to:

`if (www.error != null && !string.IsNullOrEmpty(www.error))`

Hope this helps out, I haven't used Github before so I'm not too sure how to use it, so hopefully this comment will help others out and get passed on to be fixed in the source code.

**Comment by loicteixeira** [comment]
Hi @DanielJMus, thanks for your help and detailed explanation.

If you're interested in learning more about Git, GitHub and open source contribution, feel free to follow [this guide](https://www.sammyk.me/how-to-contribute-to-an-open-source-project-on-github) to submit a fix (you can skip `Submit a feature proposal` and stop after `Submit a pull request (PR)`). Basically you make a copy of this repository under your own account (so you have write rights), make a fix and then request me to pull your fix into my repository.

No pressure though, I'm happy to do it myself and include this in the next patch.

**Comment by DanielJMus** [comment]
Thanks @loicteixeira, I created a pull request, and thank you for the guide!

**Comment by mgeorgedeveloper** [comment]
if (!string.IsNullOrEmpty(www.error)) will work OK. No need for the extra null check before string.IsNullOrEmpty.

**Comment by loicteixeira** [comment]
Thanks @DanielJMus for the contribution (I'll merge it next week) and thanks @mgeorgedeveloper for the very pertinent suggestion (I'll update the code accordingly)!
