### ISSUE TITLE
Bump minimum version

### ISSUE THREAD

**Issue by loicteixeira** [loicteixeira/gj-unity-api#83]
So far, the minimum version to use the API is `Unity 5.0.1` (as of [v2.1.0](https://github.com/loicteixeira/gj-unity-api/releases/tag/v2.1.0)) which means the package has to be generated with `Unity 5.0.1`.

It's probably not necessary to support that far back and could probably be bumped to something more recent. Unity 2017 maybe?

**Comment by InfectedBytes** [comment]
Bumping the minimum version is a good idea, but I'm not sure if we should jump directly to Unity 2017.
Unity 2017 is awesome, but I think there are still many users in the Unity 5 cycle.
I don't have fresh numbers of the usage distribution, but in June it kinda looked like this:
Unity 5.6 and 2017: 65% (unfortunately I don't have separate numbers for them)
Unity 5.5: 18%
Unity 5.4: 8%
Unity 5.3: 5%
Unity 5.2: 1%
<Unity 5.2: ~3%
So we could savely ignore all versions below 5.3 and still cover 95%.
We could even go up to 5.5 (covering 83%), but I think we should not bump the minimum version above that (at least for now)

**Comment by loicteixeira** [comment]
Fair point. 2017 would leave too many developers behind.

So it seems to be between `5.3` and `5.5`. As a side note, I had open an issue to investigate `UnityWebRequest` as a replacement of `WWW` (see #78 for more info). It was introduced in `5.4` so the minimum version would need to be that in order to experiment with it.

**Comment by loicteixeira** [comment]
Issues are now tracked at [InfectedBytes/gj-unity-api/issues](https://github.com/InfectedBytes/gj-unity-api/).
